services:
  db:
    container_name: md-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    volumes:
      - md_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: md-redis
    image: redis:7-alpine
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    networks:
      - backend

volumes:
  md_data:
  redis_data:

networks:
  backend:
